services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: chicken_nation_backend
#    env_file:
#      - .env
#    # environment:
#    #   - DATABASE_URL=postgresql://postgres:postgres@database:5432/chicken_nation
#    #   - PORT=8081
#    #   - REDIS_HOST=redis
#    #   - REDIS_PORT=6379
#    ports:
#      - "8082:8081"
#    depends_on:
#      # - database
#      - redis
#    networks:
#      - chicken_nation_network
#    restart: unless-stopped

  redis:
    image: redis:8.2.1-alpine
    container_name: chicken_nation_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chicken_nation_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  chicken_nation_network:
    driver: bridge
